platform :ios, "6.0"

pod 'cocoa-oauth', '~> 0.0.1'
pod 'OMGHTTPURLRQ', :git=>'https://github.com/pixnet/OMGHTTPURLRQ.git'
#pod 'LROAuth2Client-PIXNET', :git => 'https://github.com/dolphinSuPixnet/LROAuth2Client.git', :tag => '0.2'
#pod 'RPJSONValidator', '~> 0.1.2'

target :KiwiTests, :exclusive => true do
pod 'Kiwi', '~> 2.4.0'
pod 'OCMock', '~> 3.1.5'
end
target :SpectaTests, :exclusive => true do
pod 'Expecta', '~> 1.0.3'
pod 'Specta', '~> 1.0.4'
pod 'Nocilla', '~> 0.10.0'
end
target :SpectaTestVerifyCellphone, :exclusive => true do
pod 'Expecta', '~> 1.0.3'
pod 'Specta', '~> 1.0.4'
pod 'uicontrol-blocks', '~> 1.1.0'
end
target :SpectaTestAlbumClass, :exclusive => true do
pod 'Expecta', '~> 1.0.3'
pod 'Specta', '~> 1.0.4'
end
target :SpectaTestInOAuth1, :exclusive => true do
pod 'Expecta', '~> 1.0.3'
pod 'Specta', '~> 1.0.4'
end
target :ErrorDescriptionTests, :exclusive => true do
pod 'Nocilla', '~> 0.10.0'
pod 'Expecta', '~> 1.0.3'
pod 'Specta', '~> 1.0.4'
end
target :SpectaTestBlogClass, :exclusive => true do
pod 'Expecta', '~> 1.0.3'
pod 'Specta', '~> 1.0.4'
pod 'Nocilla', '~> 0.10.0'
end
