platform :ios, "6.0"

pod 'cocoa-oauth', '~> 0.0.1'
#pod 'LROAuth2Client-PIXNET', :git => 'https://github.com/dolphinSuPixnet/LROAuth2Client.git', :tag => '0.2'
#pod 'RPJSONValidator', '~> 0.1.2'

#target :PIXNET-iOS-SDKTests, :exclusive => true do
#  pod 'Kiwi', '~> 2.3.0'
#end