platform :ios, "6.0"

pod 'cocoa-oauth', '~> 0.0.1'
pod 'OMGHTTPURLRQ', '~> 2.1'
#pod 'LROAuth2Client-PIXNET', :git => 'https://github.com/dolphinSuPixnet/LROAuth2Client.git', :tag => '0.2'
#pod 'RPJSONValidator', '~> 0.1.2'

target :KiwiTests, :exclusive => true do
  pod 'Kiwi'
  pod 'OCMock'
end
target :SpectaTests, :exclusive => true do
  pod 'Expecta'
  pod 'Specta'
end
target :SpectaTestVerifyCellphone, :exclusive => true do
  pod 'Expecta'
  pod 'Specta'
  pod 'uicontrol-blocks'
end
target :SpectaTestAlbumClass, :exclusive => true do
    pod 'Expecta'
    pod 'Specta'
end
target :SpectaTestInOAuth1, :exclusive => true do
    pod 'Expecta'
    pod 'Specta'
end
target :ErrorDescriptionTests, :exclusive => true do
  pod 'Nocilla'
  pod 'Expecta'
  pod 'Specta'
end